//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortali_H5190062
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Begeni
    {
        public int Id { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<int> HaberId { get; set; }
    
        public virtual tbl_Haberler tbl_Haberler { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
